/* Generated by scripts/generate-agent-knowledge.mjs from component-manifest.json and softn-docs.json; do not edit.
   Regenerate with: npm run generate:knowledge -w @softn/studio */

export const KNOWLEDGE_SOURCES = {"manifest":"32c75224bd25145e","docs":"896d2f4c671aa30f"} as const;

export interface ComponentIndexEntry { name: string; category: string; purpose: string; registered: boolean }
export const COMPONENT_INDEX: ComponentIndexEntry[] = [
 {
  "name": "Accordion",
  "category": "minimal",
  "purpose": "Collapsible sections from an items list; one or many open.",
  "registered": true
 },
 {
  "name": "Alert",
  "category": "minimal",
  "purpose": "An inline message box: info, success, warning or error, optionally dismissible.",
  "registered": true
 },
 {
  "name": "AnimatedBox",
  "category": "animation",
  "purpose": "Wraps children in an entrance or attention animation.",
  "registered": true
 },
 {
  "name": "AnimatedNumber",
  "category": "animation",
  "purpose": "A number that counts up or down to its value.",
  "registered": true
 },
 {
  "name": "App",
  "category": "minimal",
  "purpose": "The root of a page: theme and base layout. Every page's template starts with <App>.",
  "registered": true
 },
 {
  "name": "AreaChart",
  "category": "charts",
  "purpose": "Filled line chart for one or more series.",
  "registered": true
 },
 {
  "name": "AudioStream",
  "category": "media",
  "purpose": "Plays audio samples the logic produces, in real time.",
  "registered": true
 },
 {
  "name": "Avatar",
  "category": "minimal",
  "purpose": "A person's picture, or their initials when there is none.",
  "registered": true
 },
 {
  "name": "AvatarGroup",
  "category": "helper",
  "purpose": "Stacked avatars (a helper inside Avatar; not a registered tag).",
  "registered": false
 },
 {
  "name": "Badge",
  "category": "minimal",
  "purpose": "A small count or status label.",
  "registered": true
 },
 {
  "name": "BarChart",
  "category": "charts",
  "purpose": "Vertical or horizontal bar chart; grouped or stacked series.",
  "registered": true
 },
 {
  "name": "Box",
  "category": "minimal",
  "purpose": "A plain box with padding, background, border, radius and shadow props.",
  "registered": true
 },
 {
  "name": "Breadcrumb",
  "category": "minimal",
  "purpose": "The path to the current page, as links.",
  "registered": true
 },
 {
  "name": "Button",
  "category": "minimal",
  "purpose": "A clickable button: variants, sizes, loading and disabled states.",
  "registered": true
 },
 {
  "name": "Camera",
  "category": "media",
  "purpose": "Live camera view that can capture a photo or video (needs the camera permission).",
  "registered": true
 },
 {
  "name": "Card",
  "category": "minimal",
  "purpose": "A bordered or elevated panel, with an optional title and subtitle.",
  "registered": true
 },
 {
  "name": "Center",
  "category": "minimal",
  "purpose": "Centres its children horizontally and vertically.",
  "registered": true
 },
 {
  "name": "Checkbox",
  "category": "minimal",
  "purpose": "A checkbox with a label; bind with :bind or :checked.",
  "registered": true
 },
 {
  "name": "CodeEditor",
  "category": "editors",
  "purpose": "An editor for source code with syntax highlighting.",
  "registered": true
 },
 {
  "name": "Collapse",
  "category": "minimal",
  "purpose": "Shows or hides its children with an animation.",
  "registered": true
 },
 {
  "name": "ColorPicker",
  "category": "minimal",
  "purpose": "Choose a colour, with optional presets.",
  "registered": true
 },
 {
  "name": "Container",
  "category": "minimal",
  "purpose": "Centres content at a maximum width (sm to xl).",
  "registered": true
 },
 {
  "name": "Content",
  "category": "minimal",
  "purpose": "The main content region of a Layout, optionally per route.",
  "registered": true
 },
 {
  "name": "DataGrid",
  "category": "minimal",
  "purpose": "A large, virtualised data table with sorting and selection.",
  "registered": true
 },
 {
  "name": "DatePicker",
  "category": "minimal",
  "purpose": "Choose a date.",
  "registered": true
 },
 {
  "name": "Divider",
  "category": "minimal",
  "purpose": "A horizontal or vertical rule, optionally labelled.",
  "registered": true
 },
 {
  "name": "DPad",
  "category": "minimal",
  "purpose": "An on-screen directional pad for games: press and release per direction.",
  "registered": true
 },
 {
  "name": "Draggable",
  "category": "animation",
  "purpose": "Makes its children draggable within bounds.",
  "registered": true
 },
 {
  "name": "Drawer",
  "category": "minimal",
  "purpose": "A panel that slides in from an edge.",
  "registered": true
 },
 {
  "name": "EmptyFolder",
  "category": "helper",
  "purpose": "Preset empty state for an empty folder (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "EmptyList",
  "category": "helper",
  "purpose": "Preset empty state for an empty list (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "EmptySearch",
  "category": "helper",
  "purpose": "Preset empty state for no search results (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "EmptyState",
  "category": "minimal",
  "purpose": "What to show when there is nothing yet: icon, title, description, action.",
  "registered": true
 },
 {
  "name": "FileChooser",
  "category": "minimal",
  "purpose": "Pick files from the device, as a button or a drop zone.",
  "registered": true
 },
 {
  "name": "Form",
  "category": "minimal",
  "purpose": "Groups inputs and submits them together.",
  "registered": true
 },
 {
  "name": "GaugeChart",
  "category": "charts",
  "purpose": "A single value on a dial, with thresholds.",
  "registered": true
 },
 {
  "name": "Grid",
  "category": "minimal",
  "purpose": "CSS grid layout: columns, rows and gaps.",
  "registered": true
 },
 {
  "name": "Header",
  "category": "minimal",
  "purpose": "A top bar with a title; can stick to the top.",
  "registered": true
 },
 {
  "name": "Heading",
  "category": "minimal",
  "purpose": "A heading, h1 to h6 (level).",
  "registered": true
 },
 {
  "name": "Icon",
  "category": "minimal",
  "purpose": "A named icon from the built-in set, or an SVG.",
  "registered": true
 },
 {
  "name": "Image",
  "category": "minimal",
  "purpose": "An image with fit, position and radius.",
  "registered": true
 },
 {
  "name": "Input",
  "category": "minimal",
  "purpose": "A single-line text field: text, email, password, number and more.",
  "registered": true
 },
 {
  "name": "Layout",
  "category": "minimal",
  "purpose": "Page layout frame that holds Header, Sidebar and Content.",
  "registered": true
 },
 {
  "name": "LineChart",
  "category": "charts",
  "purpose": "Line chart for one or more series.",
  "registered": true
 },
 {
  "name": "List",
  "category": "minimal",
  "purpose": "A vertical list of ListItem rows.",
  "registered": true
 },
 {
  "name": "ListItem",
  "category": "minimal",
  "purpose": "One row of a List, with leading and trailing content.",
  "registered": true
 },
 {
  "name": "Loop",
  "category": "minimal",
  "purpose": "Calls @tick on an interval while running: a game or animation clock.",
  "registered": true
 },
 {
  "name": "MarkdownEditor",
  "category": "editors",
  "purpose": "Edit Markdown with a live preview.",
  "registered": true
 },
 {
  "name": "Marquee",
  "category": "animation",
  "purpose": "Scrolls its children continuously.",
  "registered": true
 },
 {
  "name": "Menu",
  "category": "minimal",
  "purpose": "A dropdown menu of items from a trigger.",
  "registered": true
 },
 {
  "name": "Microphone",
  "category": "media",
  "purpose": "Records clips or streams microphone input (needs the mic permission).",
  "registered": true
 },
 {
  "name": "Modal",
  "category": "minimal",
  "purpose": "A dialog over the page; open with open/isOpen, close with @close.",
  "registered": true
 },
 {
  "name": "NavItem",
  "category": "minimal",
  "purpose": "A navigation link or button, marked active for the current page.",
  "registered": true
 },
 {
  "name": "Pagination",
  "category": "minimal",
  "purpose": "Page controls for a long list or table.",
  "registered": true
 },
 {
  "name": "PanView",
  "category": "animation",
  "purpose": "A draggable, zoomable viewport over large content.",
  "registered": true
 },
 {
  "name": "PieChart",
  "category": "charts",
  "purpose": "Pie or donut chart.",
  "registered": true
 },
 {
  "name": "PixelCanvas",
  "category": "minimal",
  "purpose": "A pixel framebuffer drawn from the logic: emulators, retro games.",
  "registered": true
 },
 {
  "name": "PixelGrid",
  "category": "minimal",
  "purpose": "A grid of cells for board and tile games.",
  "registered": true
 },
 {
  "name": "Popover",
  "category": "minimal",
  "purpose": "Floating content anchored to a trigger, on click or hover.",
  "registered": true
 },
 {
  "name": "Progress",
  "category": "minimal",
  "purpose": "A progress bar.",
  "registered": true
 },
 {
  "name": "QRCode",
  "category": "media",
  "purpose": "Draws a QR code for a value.",
  "registered": true
 },
 {
  "name": "QRReader",
  "category": "media",
  "purpose": "Scans QR codes with the camera (needs the camera permission).",
  "registered": true
 },
 {
  "name": "RadarChart",
  "category": "charts",
  "purpose": "Radar (spider) chart across several axes.",
  "registered": true
 },
 {
  "name": "Radio",
  "category": "minimal",
  "purpose": "Choose one of several options.",
  "registered": true
 },
 {
  "name": "RichTextEditor",
  "category": "editors",
  "purpose": "Formatted text editing with a toolbar.",
  "registered": true
 },
 {
  "name": "Scene3D",
  "category": "scene3d",
  "purpose": "A Three.js 3D scene from a list of objects, lights and a camera.",
  "registered": true
 },
 {
  "name": "Section",
  "category": "minimal",
  "purpose": "A titled section of a page, with an optional action.",
  "registered": true
 },
 {
  "name": "Select",
  "category": "minimal",
  "purpose": "A dropdown to choose one option.",
  "registered": true
 },
 {
  "name": "Sidebar",
  "category": "minimal",
  "purpose": "A side column, collapsible.",
  "registered": true
 },
 {
  "name": "Skeleton",
  "category": "helper",
  "purpose": "Loading placeholder shapes (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "SkeletonCard",
  "category": "helper",
  "purpose": "Loading placeholder for a card (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "SkeletonCircle",
  "category": "helper",
  "purpose": "Loading placeholder for an avatar (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "SkeletonText",
  "category": "helper",
  "purpose": "Loading placeholder for lines of text (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "Slider",
  "category": "minimal",
  "purpose": "Choose a number in a range by dragging.",
  "registered": true
 },
 {
  "name": "SmartCards",
  "category": "smart",
  "purpose": "Cards generated from records, mapping fields to title, image, badges.",
  "registered": true
 },
 {
  "name": "SmartForm",
  "category": "smart",
  "purpose": "A form generated from field definitions.",
  "registered": true
 },
 {
  "name": "SmartGrid",
  "category": "smart",
  "purpose": "A searchable, sortable table generated from records.",
  "registered": true
 },
 {
  "name": "SmartList",
  "category": "smart",
  "purpose": "A list generated from records, mapping fields to lines.",
  "registered": true
 },
 {
  "name": "SmartStats",
  "category": "smart",
  "purpose": "Stat tiles with trends.",
  "registered": true
 },
 {
  "name": "SmartTimeline",
  "category": "smart",
  "purpose": "A timeline of records.",
  "registered": true
 },
 {
  "name": "SmartView",
  "category": "smart",
  "purpose": "Shows one record's fields as a card, list or grid.",
  "registered": true
 },
 {
  "name": "SortableList",
  "category": "animation",
  "purpose": "A list the person can reorder by dragging.",
  "registered": true
 },
 {
  "name": "Spacer",
  "category": "minimal",
  "purpose": "Empty space, fixed or flexible.",
  "registered": true
 },
 {
  "name": "Spinner",
  "category": "minimal",
  "purpose": "A loading indicator.",
  "registered": true
 },
 {
  "name": "Split",
  "category": "minimal",
  "purpose": "Two panes with a draggable divider.",
  "registered": true
 },
 {
  "name": "Sprite",
  "category": "animation",
  "purpose": "Draws one frame of a sprite sheet: game characters.",
  "registered": true
 },
 {
  "name": "Stack",
  "category": "minimal",
  "purpose": "Lays children out in a row or column with a gap: the everyday layout.",
  "registered": true
 },
 {
  "name": "Switch",
  "category": "minimal",
  "purpose": "An on/off toggle with a label.",
  "registered": true
 },
 {
  "name": "Table",
  "category": "minimal",
  "purpose": "A table from columns [{ key, header }] and data rows.",
  "registered": true
 },
 {
  "name": "Tabs",
  "category": "minimal",
  "purpose": "Tabs from [{ key, label }]; @change receives the key.",
  "registered": true
 },
 {
  "name": "Tag",
  "category": "minimal",
  "purpose": "A small label, optionally removable.",
  "registered": true
 },
 {
  "name": "TagGroup",
  "category": "helper",
  "purpose": "Lays out several Tags (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "Text",
  "category": "minimal",
  "purpose": "A run of text: size, weight, colour, alignment, truncation.",
  "registered": true
 },
 {
  "name": "TextArea",
  "category": "minimal",
  "purpose": "A multi-line text field.",
  "registered": true
 },
 {
  "name": "TileMap",
  "category": "animation",
  "purpose": "Draws a tile map from a tileset: game levels.",
  "registered": true
 },
 {
  "name": "Toast",
  "category": "minimal",
  "purpose": "A transient notification.",
  "registered": true
 },
 {
  "name": "Tooltip",
  "category": "minimal",
  "purpose": "A hint shown on hover or focus.",
  "registered": true
 },
 {
  "name": "TooltipTrigger",
  "category": "helper",
  "purpose": "Wraps an element with a tooltip (helper; not a registered tag).",
  "registered": false
 },
 {
  "name": "TreeView",
  "category": "minimal",
  "purpose": "A tree of expandable nodes.",
  "registered": true
 },
 {
  "name": "Typewriter",
  "category": "animation",
  "purpose": "Types its text out character by character.",
  "registered": true
 }
];

export interface DocIndexEntry { slug: string; title: string; summary: string; sections: string[] }
export const DOC_INDEX: DocIndexEntry[] = [
 {
  "slug": "overview",
  "title": "SoftN documentation",
  "summary": "Build an app, keep its source, and choose where it runs. Start with an example or follow a guide from first edit to deployment.",
  "sections": [
   "welcome",
   "choose-your-route",
   "learn-the-pieces",
   "using-these-docs"
  ]
 },
 {
  "slug": "what-is-softn",
  "title": "What is SoftN?",
  "summary": "An introduction to the editable app format, the tools around it, and the choices you keep after building an app.",
  "sections": [
   "the-idea",
   "the-tools",
   "what-you-can-build",
   "what-portable-means",
   "first-step"
  ]
 },
 {
  "slug": "getting-started",
  "title": "Getting started with SoftN",
  "summary": "Start in the browser, or run the repository locally, then make your first editable app.",
  "sections": [
   "browser-first",
   "local-setup",
   "pick-a-workspace",
   "first-success",
   "next"
  ]
 },
 {
  "slug": "first-app",
  "title": "Build your first SoftN app",
  "summary": "Make a small change to Fieldnotes, then read a counter that connects the interface, its state and an event handler, in JavaScript or Python.",
  "sections": [
   "start-with-fieldnotes",
   "understand-a-small-app",
   "try-a-change",
   "check-your-export"
  ]
 },
 {
  "slug": "examples",
  "title": "Learn from SoftN examples",
  "summary": "Use Fieldnotes as a source-level tour, find the examples that ship with the repository and Studio, then explore the wider catalogue with a focused question.",
  "sections": [
   "fieldnotes",
   "read-the-flow",
   "in-the-repository",
   "catalogue",
   "customise",
   "first-experiment"
  ]
 },
 {
  "slug": "builder",
  "title": "SoftN Builder",
  "summary": "Design the interface, write logic in JavaScript or Python, model data and preview a portable app in one editable workspace.",
  "sections": [
   "where-builder-fits",
   "new-project",
   "logic-dock",
   "handlers",
   "files",
   "a-useful-workflow",
   "visual-and-code",
   "preview",
   "data-preview",
   "export"
  ]
 },
 {
  "slug": "studio",
  "title": "SoftN Studio",
  "summary": "Describe an app to an AI provider you choose, approve a plan, then inspect, test and keep the result as editable source in JavaScript or Python.",
  "sections": [
   "what-studio-does",
   "a-better-brief",
   "how-the-ai-builds",
   "preview-and-validation",
   "review-the-result",
   "files",
   "provider-and-privacy",
   "continue-editing"
  ]
 },
 {
  "slug": "runtime",
  "title": "SoftN Runtime",
  "summary": "Open bundles, switch between running apps and understand what the browser library does and does not keep.",
  "sections": [
   "opening-an-app",
   "engines",
   "workspace-lifecycle",
   "saved-library",
   "permissions-and-hosts",
   "check-an-app"
  ]
 },
 {
  "slug": "softn-app-format",
  "title": "The .softn app format",
  "summary": "What a bundle contains, how its manifest configures logic and packages, what an export leaves behind, and how to think about seeds and permissions.",
  "sections": [
   "what-is-the-file",
   "inside-the-bundle",
   "manifest-config",
   "logic-files",
   "seeds-and-live-data",
   "private-material",
   "identity-and-compatibility"
  ]
 },
 {
  "slug": "ui-language",
  "title": "The SoftN UI language",
  "summary": "Read component tags, expressions, bindings, event handlers and control flow, and link a page to its logic file.",
  "sections": [
   "the-shape",
   "properties",
   "bindings",
   "control-flow",
   "composition"
  ]
 },
 {
  "slug": "logic-zipp",
  "title": "App logic in JavaScript or Python",
  "summary": "Write an app’s behaviour in JavaScript or Python, see what the two share, and understand the ZIPP engine and the host APIs around it.",
  "sections": [
   "what-runs",
   "the-contract",
   "state-and-actions",
   "engine-host",
   "version",
   "server",
   "next"
  ]
 },
 {
  "slug": "state-events",
  "title": "State, events and app lifecycle",
  "summary": "Connect user actions to state, understand event data, and distinguish a running screen from durable records.",
  "sections": [
   "state-round-trip",
   "events",
   "pointer-keyboard",
   "lifecycle",
   "debugging"
  ]
 },
 {
  "slug": "components",
  "title": "SoftN component guide",
  "summary": "Find a sensible starting component for layouts, forms, data, charts, media, animation and richer apps.",
  "sections": [
   "choose-by-job",
   "everyday-components",
   "records-and-dashboards",
   "interactive-media",
   "how-to-learn"
  ]
 },
 {
  "slug": "forms-tables-dashboards",
  "title": "Forms, tables and dashboards",
  "summary": "Build a useful record workflow before adding extra screens, summaries and visual polish.",
  "sections": [
   "one-record-flow",
   "smart-form",
   "smart-grid",
   "summaries",
   "acceptance"
  ]
 },
 {
  "slug": "xdb-data",
  "title": "Local app data with XDB",
  "summary": "Understand collections, record operations, seeds, app identity and optional synchronisation.",
  "sections": [
   "where-xdb-fits",
   "operations",
   "schema-and-seeds",
   "identity",
   "sync"
  ]
 },
 {
  "slug": "assets-themes-responsive",
  "title": "Assets, themes and responsive layouts",
  "summary": "Keep an app readable, portable and testable across sizes without relying on your own browser cache.",
  "sections": [
   "portable-assets",
   "themes",
   "responsive",
   "network-dependencies",
   "finish"
  ]
 },
 {
  "slug": "architecture",
  "title": "How SoftN, ZIPP and XDB fit together",
  "summary": "A readable map of the interface, guest logic, data and hosting responsibilities.",
  "sections": [
   "a-map",
   "ui",
   "composer",
   "logic",
   "data",
   "portability",
   "next"
  ]
 },
 {
  "slug": "audio-media",
  "title": "Audio, microphone and media",
  "summary": "Add sound deliberately, understand autoplay, and distinguish playback from access to a person’s microphone or camera.",
  "sections": [
   "playback",
   "autoplay",
   "capture",
   "test-media"
  ]
 },
 {
  "slug": "threejs-games",
  "title": "3D apps and games with SoftN",
  "summary": "Combine a readable interface with scenes, controls, animation and sound without confusing rendering with engine execution.",
  "sections": [
   "the-pieces",
   "choose-dimensions",
   "input",
   "performance",
   "release-check"
  ]
 },
 {
  "slug": "machine-learning-torch",
  "title": "Machine learning with torch",
  "summary": "Train and run small neural networks in a Python app, in the browser, with ZIPP’s torch: declare it, keep tensors in Python and show plain numbers.",
  "sections": [
   "what-it-is",
   "declare",
   "train",
   "state",
   "pace",
   "limits",
   "example"
  ]
 },
 {
  "slug": "permissions",
  "title": "Permissions and sandboxing",
  "summary": "Understand requested capabilities, host grants, browser consent and the limits of an editable client bundle.",
  "sections": [
   "three-questions",
   "declaration",
   "sandbox",
   "identity",
   "test-denial",
   "scope"
  ]
 },
 {
  "slug": "offline-local-data",
  "title": "Offline use, local data and app identity",
  "summary": "Know what your browser keeps, what an export carries and what needs a separate backup or server.",
  "sections": [
   "local-first",
   "four-things",
   "browser",
   "updates",
   "offline-check"
  ]
 },
 {
  "slug": "language-support",
  "title": "Python logic",
  "summary": "Write an app’s client logic in Python: link a .py file, keep state in top-level names, change it with global, and call host capabilities through import softn.",
  "sections": [
   "start",
   "contract",
   "handlers",
   "capabilities",
   "not-available",
   "names",
   "engines",
   "keep-going"
  ]
 },
 {
  "slug": "hosting",
  "title": "Hosting and deploying SoftN apps",
  "summary": "Choose between opening a bundle, publishing an app, hosting one website or connecting a private backend.",
  "sections": [
   "choose-first",
   "routes",
   "client-server",
   "before-release",
   "build-commands"
  ]
 },
 {
  "slug": "single-app-runtime",
  "title": "Host one app on its own website",
  "summary": "Ship one SoftN app on its own website: build the unbranded runtime, point runtime.config.json at your bundle, choose how permissions are granted, and keep the identity that your visitors’ records depend on.",
  "sections": [
   "what-it-is",
   "build-route",
   "configure",
   "permissions",
   "identity",
   "variants",
   "private-resources",
   "acceptance"
  ]
 },
 {
  "slug": "private-backend",
  "title": "Private backends and server-side logic",
  "summary": "Keep private operations and SQLite data on the server, with a deliberate client-facing API.",
  "sections": [
   "when-needed",
   "split",
   "source-material",
   "contracts",
   "test",
   "references"
  ]
 },
 {
  "slug": "formlogic",
  "title": "SoftN and FormLogic",
  "summary": "Understand the difference between exporting an editable starter and running an authenticated connected workspace.",
  "sections": [
   "roles",
   "starter",
   "connected",
   "examples",
   "server",
   "next"
  ]
 },
 {
  "slug": "publishing",
  "title": "Publish and share a SoftN app",
  "summary": "Distinguish sharing an editable bundle, saving a project and publishing an app with a hosted page.",
  "sections": [
   "ways-to-share",
   "vocabulary",
   "description",
   "before-publish",
   "after-publish"
  ]
 },
 {
  "slug": "development",
  "title": "Develop SoftN from source",
  "summary": "Use the repository’s workspace commands and keep browser-app changes separate from rebuilding the engine.",
  "sections": [
   "requirements",
   "scripts",
   "engine",
   "tests",
   "docs"
  ]
 },
 {
  "slug": "troubleshooting",
  "title": "Troubleshooting SoftN apps",
  "summary": "Identify whether a problem belongs to the interface, logic, data, permissions, assets or host before changing several layers.",
  "sections": [
   "locate",
   "load",
   "python",
   "state",
   "records",
   "permissions",
   "media",
   "layout-offline",
   "report"
  ]
 },
 {
  "slug": "faq",
  "title": "SoftN frequently asked questions",
  "summary": "Straight answers about the app format, accounts, AI, local data, hosting, JavaScript and Python.",
  "sections": [
   "what-is",
   "file",
   "ai",
   "coding",
   "data",
   "offline",
   "javascript",
   "python",
   "torch",
   "hosting",
   "formlogic",
   "secrets",
   "license",
   "complete"
  ]
 }
];
